name: skincaredemo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  firebase_storage: ^11.6.10
  get: ^4.6.6
  shared_preferences: ^2.2.2
  loading_indicator: ^3.1.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  fl_chart: ^0.66.2
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svgs/